<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410115923 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE achata DROP FOREIGN KEY FK_565BC6F83AAF8973');
        $this->addSql('ALTER TABLE achata DROP FOREIGN KEY FK_565BC6F8A76ED395');
        $this->addSql('ALTER TABLE achata DROP FOREIGN KEY FK_565BC6F8D725330D');
        $this->addSql('ALTER TABLE achata DROP FOREIGN KEY FK_565BC6F8F347EFB');
        $this->addSql('ALTER TABLE actifa DROP FOREIGN KEY FK_3A730FB4A76ED395');
        $this->addSql('ALTER TABLE actifa DROP FOREIGN KEY FK_3A730FB4D725330D');
        $this->addSql('ALTER TABLE balancea DROP FOREIGN KEY FK_7006D7D922A5DBC9');
        $this->addSql('ALTER TABLE balancea DROP FOREIGN KEY FK_7006D7D9A76ED395');
        $this->addSql('ALTER TABLE balancea DROP FOREIGN KEY FK_7006D7D9D725330D');
        $this->addSql('ALTER TABLE balancea DROP FOREIGN KEY FK_7006D7D9EA82AF8F');
        $this->addSql('ALTER TABLE bondcommande DROP FOREIGN KEY FK_58BE72D7F347EFB');
        $this->addSql('ALTER TABLE bondcommandea DROP FOREIGN KEY FK_CB36678EF347EFB');
        $this->addSql('ALTER TABLE caissea DROP FOREIGN KEY FK_89694EC6A76ED395');
        $this->addSql('ALTER TABLE caissea DROP FOREIGN KEY FK_89694EC6D725330D');
        $this->addSql('ALTER TABLE credit_fourniseur DROP FOREIGN KEY FK_AD9F5770670C757F');
        $this->addSql('ALTER TABLE credit_fourniseur DROP FOREIGN KEY FK_AD9F5770A76ED395');
        $this->addSql('ALTER TABLE credit_fourniseur DROP FOREIGN KEY FK_AD9F5770D725330D');
        $this->addSql('ALTER TABLE depensea DROP FOREIGN KEY FK_DF943D1DA76ED395');
        $this->addSql('ALTER TABLE depensea DROP FOREIGN KEY FK_DF943D1DD725330D');
        $this->addSql('ALTER TABLE depenseactif DROP FOREIGN KEY FK_C6402A2440E1C722');
        $this->addSql('ALTER TABLE depenseactif DROP FOREIGN KEY FK_C6402A24A76ED395');
        $this->addSql('ALTER TABLE depenseactif DROP FOREIGN KEY FK_C6402A24D725330D');
        $this->addSql('ALTER TABLE depenseactifa DROP FOREIGN KEY FK_EF1C3A7040E1C722');
        $this->addSql('ALTER TABLE depenseactifa DROP FOREIGN KEY FK_EF1C3A70A76ED395');
        $this->addSql('ALTER TABLE depenseactifa DROP FOREIGN KEY FK_EF1C3A70D725330D');
        $this->addSql('ALTER TABLE depensepassif DROP FOREIGN KEY FK_F3A20F9549B26346');
        $this->addSql('ALTER TABLE depensepassif DROP FOREIGN KEY FK_F3A20F95A76ED395');
        $this->addSql('ALTER TABLE depensepassif DROP FOREIGN KEY FK_F3A20F95D725330D');
        $this->addSql('ALTER TABLE depensepassifa DROP FOREIGN KEY FK_534F5B4F49B26346');
        $this->addSql('ALTER TABLE depensepassifa DROP FOREIGN KEY FK_534F5B4FA76ED395');
        $this->addSql('ALTER TABLE depensepassifa DROP FOREIGN KEY FK_534F5B4FD725330D');
        $this->addSql('ALTER TABLE employer_agence DROP FOREIGN KEY FK_3B8E660E41CD9E7A');
        $this->addSql('ALTER TABLE employer_agence DROP FOREIGN KEY FK_3B8E660ED725330D');
        $this->addSql('ALTER TABLE emprunta DROP FOREIGN KEY FK_322EFBDBA76ED395');
        $this->addSql('ALTER TABLE emprunta DROP FOREIGN KEY FK_322EFBDBD725330D');
        $this->addSql('ALTER TABLE facturea DROP FOREIGN KEY FK_37E66ADD19EB6921');
        $this->addSql('ALTER TABLE facturea DROP FOREIGN KEY FK_37E66ADD7DC7170A');
        $this->addSql('ALTER TABLE facturea DROP FOREIGN KEY FK_37E66ADDA76ED395');
        $this->addSql('ALTER TABLE facturea DROP FOREIGN KEY FK_37E66ADDD725330D');
        $this->addSql('ALTER TABLE facturea DROP FOREIGN KEY FK_37E66ADDF347EFB');
        $this->addSql('ALTER TABLE fournisseura DROP FOREIGN KEY FK_3098A39A76ED395');
        $this->addSql('ALTER TABLE fournisseura DROP FOREIGN KEY FK_3098A39D725330D');
        $this->addSql('ALTER TABLE fournisseura_produita DROP FOREIGN KEY FK_E8A4154A37013DDB');
        $this->addSql('ALTER TABLE fournisseura_produita DROP FOREIGN KEY FK_E8A4154ADDBC42E9');
        $this->addSql('ALTER TABLE historiquea DROP FOREIGN KEY FK_FC1400DA973392E5');
        $this->addSql('ALTER TABLE historiquea DROP FOREIGN KEY FK_FC1400DAD725330D');
        $this->addSql('ALTER TABLE immobilisationa DROP FOREIGN KEY FK_FEA74340A76ED395');
        $this->addSql('ALTER TABLE immobilisationa DROP FOREIGN KEY FK_FEA74340D725330D');
        $this->addSql('ALTER TABLE inventairea DROP FOREIGN KEY FK_F57C7A04A76ED395');
        $this->addSql('ALTER TABLE inventairea DROP FOREIGN KEY FK_F57C7A04D725330D');
        $this->addSql('ALTER TABLE inventairea DROP FOREIGN KEY FK_F57C7A04F347EFB');
        $this->addSql('ALTER TABLE inventairecaissea DROP FOREIGN KEY FK_FDAE5AB1A76ED395');
        $this->addSql('ALTER TABLE inventairecaissea DROP FOREIGN KEY FK_FDAE5AB1D725330D');
        $this->addSql('ALTER TABLE magasina DROP FOREIGN KEY FK_8FF1E6E9A76ED395');
        $this->addSql('ALTER TABLE magasina DROP FOREIGN KEY FK_8FF1E6E9D725330D');
        $this->addSql('ALTER TABLE magasina DROP FOREIGN KEY FK_8FF1E6E9F347EFB');
        $this->addSql('ALTER TABLE passifa DROP FOREIGN KEY FK_CF9332D3A76ED395');
        $this->addSql('ALTER TABLE passifa DROP FOREIGN KEY FK_CF9332D3D725330D');
        $this->addSql('ALTER TABLE produita DROP FOREIGN KEY FK_8F8CEC5AA76ED395');
        $this->addSql('ALTER TABLE produita DROP FOREIGN KEY FK_8F8CEC5AD725330D');
        $this->addSql('ALTER TABLE prospectiona DROP FOREIGN KEY FK_CE1D2EA76ED395');
        $this->addSql('ALTER TABLE prospectiona DROP FOREIGN KEY FK_CE1D2ED725330D');
        $this->addSql('ALTER TABLE quantiteproduita DROP FOREIGN KEY FK_ACCD6C6C7DC7170A');
        $this->addSql('ALTER TABLE quantiteproduita DROP FOREIGN KEY FK_ACCD6C6CA76ED395');
        $this->addSql('ALTER TABLE quantiteproduita DROP FOREIGN KEY FK_ACCD6C6CF347EFB');
        $this->addSql('ALTER TABLE remboursementa DROP FOREIGN KEY FK_2EC8D963A76ED395');
        $this->addSql('ALTER TABLE remboursementa DROP FOREIGN KEY FK_2EC8D963AE7FEF94');
        $this->addSql('ALTER TABLE remboursementa DROP FOREIGN KEY FK_2EC8D963D725330D');
        $this->addSql('ALTER TABLE retraita DROP FOREIGN KEY FK_361A19D555D4B1AE');
        $this->addSql('ALTER TABLE retraita DROP FOREIGN KEY FK_361A19D5A76ED395');
        $this->addSql('ALTER TABLE salairea DROP FOREIGN KEY FK_4024179241CD9E7A');
        $this->addSql('ALTER TABLE salairea DROP FOREIGN KEY FK_40241792A76ED395');
        $this->addSql('ALTER TABLE salairea DROP FOREIGN KEY FK_40241792D725330D');
        $this->addSql('ALTER TABLE socialesa DROP FOREIGN KEY FK_AFCF975EA76ED395');
        $this->addSql('ALTER TABLE socialesa DROP FOREIGN KEY FK_AFCF975ED725330D');
        $this->addSql('ALTER TABLE tempagence DROP FOREIGN KEY FK_30A8D1D2A76ED395');
        $this->addSql('ALTER TABLE tempagence DROP FOREIGN KEY FK_30A8D1D2D725330D');
        $this->addSql('ALTER TABLE transferta DROP FOREIGN KEY FK_C029B9F3A76ED395');
        $this->addSql('ALTER TABLE transferta DROP FOREIGN KEY FK_C029B9F3C75111AD');
        $this->addSql('ALTER TABLE transferta DROP FOREIGN KEY FK_C029B9F3D725330D');
        $this->addSql('ALTER TABLE transferta DROP FOREIGN KEY FK_C029B9F3F347EFB');
        $this->addSql('ALTER TABLE tresoreriea DROP FOREIGN KEY FK_90D006D0A76ED395');
        $this->addSql('ALTER TABLE tresoreriea DROP FOREIGN KEY FK_90D006D0D725330D');
        $this->addSql('ALTER TABLE ventea DROP FOREIGN KEY FK_AB971C2C19EB6921');
        $this->addSql('ALTER TABLE ventea DROP FOREIGN KEY FK_AB971C2CA76ED395');
        $this->addSql('ALTER TABLE ventea DROP FOREIGN KEY FK_AB971C2CD725330D');
        $this->addSql('ALTER TABLE ventea DROP FOREIGN KEY FK_AB971C2CF347EFB');
        $this->addSql('ALTER TABLE versementa DROP FOREIGN KEY FK_4F23073319EB6921');
        $this->addSql('ALTER TABLE versementa DROP FOREIGN KEY FK_4F230733A76ED395');
        $this->addSql('ALTER TABLE versementa DROP FOREIGN KEY FK_4F230733D725330D');
        $this->addSql('DROP TABLE achata');
        $this->addSql('DROP TABLE actifa');
        $this->addSql('DROP TABLE balancea');
        $this->addSql('DROP TABLE bondcommande');
        $this->addSql('DROP TABLE bondcommandea');
        $this->addSql('DROP TABLE caissea');
        $this->addSql('DROP TABLE credit_fourniseur');
        $this->addSql('DROP TABLE depensea');
        $this->addSql('DROP TABLE depenseactif');
        $this->addSql('DROP TABLE depenseactifa');
        $this->addSql('DROP TABLE depensepassif');
        $this->addSql('DROP TABLE depensepassifa');
        $this->addSql('DROP TABLE employer_agence');
        $this->addSql('DROP TABLE emprunta');
        $this->addSql('DROP TABLE facturea');
        $this->addSql('DROP TABLE fournisseura');
        $this->addSql('DROP TABLE fournisseura_produita');
        $this->addSql('DROP TABLE historiquea');
        $this->addSql('DROP TABLE immobilisationa');
        $this->addSql('DROP TABLE inventairea');
        $this->addSql('DROP TABLE inventairecaissea');
        $this->addSql('DROP TABLE limite');
        $this->addSql('DROP TABLE magasina');
        $this->addSql('DROP TABLE passifa');
        $this->addSql('DROP TABLE produita');
        $this->addSql('DROP TABLE prospectiona');
        $this->addSql('DROP TABLE quantiteproduita');
        $this->addSql('DROP TABLE remboursementa');
        $this->addSql('DROP TABLE retraita');
        $this->addSql('DROP TABLE salairea');
        $this->addSql('DROP TABLE socialesa');
        $this->addSql('DROP TABLE tempagence');
        $this->addSql('DROP TABLE transferta');
        $this->addSql('DROP TABLE tresoreriea');
        $this->addSql('DROP TABLE ventea');
        $this->addSql('DROP TABLE versementa');
        $this->addSql('ALTER TABLE depenses ADD reference VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE achata (id INT AUTO_INCREMENT NOT NULL, produit_id INT NOT NULL, forunisseur_id INT NOT NULL, user_id INT NOT NULL, agence_id INT DEFAULT NULL, prix DOUBLE PRECISION NOT NULL, quantite DOUBLE PRECISION NOT NULL, montant DOUBLE PRECISION NOT NULL, createdAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, image JSON DEFAULT NULL, reference VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_565BC6F83AAF8973 (forunisseur_id), INDEX IDX_565BC6F8A76ED395 (user_id), INDEX IDX_565BC6F8D725330D (agence_id), INDEX IDX_565BC6F8F347EFB (produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE actifa (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, brut DOUBLE PRECISION NOT NULL, amortissement DOUBLE PRECISION NOT NULL, net DOUBLE PRECISION NOT NULL, created DATE NOT NULL, cathegorie VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, ordre INT NOT NULL, REF VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_3A730FB4A76ED395 (user_id), INDEX IDX_3A730FB4D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE balancea (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, Classe INT NOT NULL, Compte INT NOT NULL, intitule VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, SoldeInitialDebit DOUBLE PRECISION NOT NULL, SoldeInitialCredit DOUBLE PRECISION NOT NULL, MouvementDebit DOUBLE PRECISION NOT NULL, MouvementCredit DOUBLE PRECISION NOT NULL, SoldeFinalDebit DOUBLE PRECISION NOT NULL, SoldFinalCredit DOUBLE PRECISION NOT NULL, SoldeGlobal DOUBLE PRECISION NOT NULL, createtAt DATE NOT NULL, ActifA_id INT DEFAULT NULL, passifA_id INT DEFAULT NULL, INDEX IDX_7006D7D922A5DBC9 (passifA_id), INDEX IDX_7006D7D9A76ED395 (user_id), INDEX IDX_7006D7D9D725330D (agence_id), INDEX IDX_7006D7D9EA82AF8F (ActifA_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE bondcommande (id INT AUTO_INCREMENT NOT NULL, produit_id INT DEFAULT NULL, statut INT NOT NULL, createtAt DATE NOT NULL, limite INT NOT NULL, INDEX IDX_58BE72D7F347EFB (produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE bondcommandea (id INT AUTO_INCREMENT NOT NULL, produit_id INT DEFAULT NULL, statut INT NOT NULL, createtAt DATE NOT NULL, limite INT NOT NULL, INDEX IDX_CB36678EF347EFB (produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE caissea (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, operation VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, montant DOUBLE PRECISION NOT NULL, motif VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createAt DATE NOT NULL, INDEX IDX_89694EC6A76ED395 (user_id), INDEX IDX_89694EC6D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE credit_fourniseur (id INT AUTO_INCREMENT NOT NULL, fournisseur_id INT DEFAULT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, banque VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, delai_paiement VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, tva DOUBLE PRECISION NOT NULL, montant DOUBLE PRECISION NOT NULL, echeance VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createt_at DATE NOT NULL, INDEX IDX_AD9F5770670C757F (fournisseur_id), INDEX IDX_AD9F5770A76ED395 (user_id), INDEX IDX_AD9F5770D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE depensea (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, description VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, montant DOUBLE PRECISION NOT NULL, createdAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, reference VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_DF943D1DA76ED395 (user_id), INDEX IDX_DF943D1DD725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE depenseactif (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, actif_id INT DEFAULT NULL, montant DOUBLE PRECISION NOT NULL, libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createtAd DATE NOT NULL, INDEX IDX_C6402A2440E1C722 (actif_id), INDEX IDX_C6402A24A76ED395 (user_id), INDEX IDX_C6402A24D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE depenseactifa (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, actif_id INT DEFAULT NULL, montant DOUBLE PRECISION NOT NULL, libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createtAd DATE NOT NULL, INDEX IDX_EF1C3A7040E1C722 (actif_id), INDEX IDX_EF1C3A70A76ED395 (user_id), INDEX IDX_EF1C3A70D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE depensepassif (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, passif_id INT DEFAULT NULL, montant DOUBLE PRECISION NOT NULL, libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createtAt DATE NOT NULL, INDEX IDX_F3A20F9549B26346 (passif_id), INDEX IDX_F3A20F95A76ED395 (user_id), INDEX IDX_F3A20F95D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE depensepassifa (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, passif_id INT DEFAULT NULL, montant DOUBLE PRECISION NOT NULL, libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createtAt DATE NOT NULL, INDEX IDX_534F5B4F49B26346 (passif_id), INDEX IDX_534F5B4FA76ED395 (user_id), INDEX IDX_534F5B4FD725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE employer_agence (employer_id INT NOT NULL, agence_id INT NOT NULL, INDEX IDX_3B8E660E41CD9E7A (employer_id), INDEX IDX_3B8E660ED725330D (agence_id), PRIMARY KEY(employer_id, agence_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE emprunta (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, montant DOUBLE PRECISION NOT NULL, durre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, tauxinteretdebiteur DOUBLE PRECISION NOT NULL, tauxannueleffectifglobal DOUBLE PRECISION NOT NULL, couttotal DOUBLE PRECISION NOT NULL, garantie VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, identitepreteur VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, emprunteur VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createtAt DATE NOT NULL, INDEX IDX_322EFBDBA76ED395 (user_id), INDEX IDX_322EFBDBD725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE facturea (id INT AUTO_INCREMENT NOT NULL, produit_id INT DEFAULT NULL, client_id INT DEFAULT NULL, user_id INT DEFAULT NULL, vente_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, quantite DOUBLE PRECISION NOT NULL, prix DOUBLE PRECISION NOT NULL, type VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', montant DOUBLE PRECISION NOT NULL, reference INT DEFAULT NULL, INDEX IDX_37E66ADD19EB6921 (client_id), INDEX IDX_37E66ADD7DC7170A (vente_id), INDEX IDX_37E66ADDA76ED395 (user_id), INDEX IDX_37E66ADDD725330D (agence_id), INDEX IDX_37E66ADDF347EFB (produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE fournisseura (id INT AUTO_INCREMENT NOT NULL, agence_id INT DEFAULT NULL, user_id INT DEFAULT NULL, nom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, adress VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, telephone VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createdAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', dateAchat DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', numfacture INT NOT NULL, INDEX IDX_3098A39A76ED395 (user_id), INDEX IDX_3098A39D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE fournisseura_produita (fournisseura_id INT NOT NULL, produita_id INT NOT NULL, INDEX IDX_E8A4154A37013DDB (produita_id), INDEX IDX_E8A4154ADDBC42E9 (fournisseura_id), PRIMARY KEY(fournisseura_id, produita_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE historiquea (id INT AUTO_INCREMENT NOT NULL, agence_id INT DEFAULT NULL, quantite DOUBLE PRECISION NOT NULL, createtAd DATE NOT NULL, heurecameroun VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, heureserver VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, produitA_id INT DEFAULT NULL, INDEX IDX_FC1400DA973392E5 (produitA_id), INDEX IDX_FC1400DAD725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE immobilisationa (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, Classe INT NOT NULL, Compte INT NOT NULL, libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, DateAcquisition DATE NOT NULL, PrixAcquisition DOUBLE PRECISION NOT NULL, CumulN1 DOUBLE PRECISION NOT NULL, DotationN DOUBLE PRECISION NOT NULL, CessionsSorties DOUBLE PRECISION NOT NULL, CumulN DOUBLE PRECISION NOT NULL, ValeurNetN DOUBLE PRECISION NOT NULL, createtAt DATE NOT NULL, INDEX IDX_FEA74340A76ED395 (user_id), INDEX IDX_FEA74340D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE inventairea (id INT AUTO_INCREMENT NOT NULL, produit_id INT DEFAULT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, quantite DOUBLE PRECISION NOT NULL, inventaire DOUBLE PRECISION NOT NULL, createtAt DATE NOT NULL, ecart DOUBLE PRECISION NOT NULL, justificatif VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_F57C7A04A76ED395 (user_id), INDEX IDX_F57C7A04D725330D (agence_id), INDEX IDX_F57C7A04F347EFB (produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE inventairecaissea (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, vente DOUBLE PRECISION NOT NULL, caisse DOUBLE PRECISION NOT NULL, ecart DOUBLE PRECISION NOT NULL, createtAt DATE NOT NULL, justificatif VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_FDAE5AB1A76ED395 (user_id), INDEX IDX_FDAE5AB1D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE limite (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE magasina (id INT AUTO_INCREMENT NOT NULL, agence_id INT DEFAULT NULL, user_id INT DEFAULT NULL, produit_id INT DEFAULT NULL, quantite DOUBLE PRECISION NOT NULL, createtAt DATE NOT NULL, operation JSON DEFAULT NULL, INDEX IDX_8FF1E6E9A76ED395 (user_id), INDEX IDX_8FF1E6E9D725330D (agence_id), INDEX IDX_8FF1E6E9F347EFB (produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE passifa (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, montant DOUBLE PRECISION NOT NULL, createdAt DATE NOT NULL, ordre INT NOT NULL, REF VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, cathegorie VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_CF9332D3A76ED395 (user_id), INDEX IDX_CF9332D3D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE produita (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, agence_id INT NOT NULL, nom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, prixvente DOUBLE PRECISION NOT NULL, prixachat DOUBLE PRECISION NOT NULL, quantite DOUBLE PRECISION NOT NULL, gain DOUBLE PRECISION NOT NULL, stockdebut DOUBLE PRECISION NOT NULL, cathegorie VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createdAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', type VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, expiration VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, reference VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, posologie VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_8F8CEC5AA76ED395 (user_id), INDEX IDX_8F8CEC5AD725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE prospectiona (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, telephone VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, localisation VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, speculation VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, sujet VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, souche VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, ravitaillement VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, commentaire VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createtAt DATE NOT NULL, nature VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_CE1D2EA76ED395 (user_id), INDEX IDX_CE1D2ED725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE quantiteproduita (id INT AUTO_INCREMENT NOT NULL, produit_id INT DEFAULT NULL, vente_id INT DEFAULT NULL, user_id INT DEFAULT NULL, quantite DOUBLE PRECISION NOT NULL, createAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_ACCD6C6C7DC7170A (vente_id), INDEX IDX_ACCD6C6CA76ED395 (user_id), INDEX IDX_ACCD6C6CF347EFB (produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE remboursementa (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, emprunt_id INT DEFAULT NULL, type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, contrat VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, etablissement VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, datesignature DATE NOT NULL, montant DOUBLE PRECISION NOT NULL, dateprelevement DATE NOT NULL, comptedebiter VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createtAt DATE NOT NULL, INDEX IDX_2EC8D963A76ED395 (user_id), INDEX IDX_2EC8D963AE7FEF94 (emprunt_id), INDEX IDX_2EC8D963D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE retraita (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, montant DOUBLE PRECISION NOT NULL, compte VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createtAt DATE NOT NULL, banque VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, Agence_id INT DEFAULT NULL, INDEX IDX_361A19D555D4B1AE (Agence_id), INDEX IDX_361A19D5A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE salairea (id INT AUTO_INCREMENT NOT NULL, employer_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, user_id INT DEFAULT NULL, montant DOUBLE PRECISION NOT NULL, createtAt DATE NOT NULL, status VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, salaireBrut DOUBLE PRECISION NOT NULL, cotisationSociales DOUBLE PRECISION NOT NULL, impots DOUBLE PRECISION NOT NULL, type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_4024179241CD9E7A (employer_id), INDEX IDX_40241792A76ED395 (user_id), INDEX IDX_40241792D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE socialesa (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, numeroCotisation VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, profession VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, cni VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, du VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, ville VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, parent VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, identite VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, delivree VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, city VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, createtAt DATE NOT NULL, INDEX IDX_AFCF975EA76ED395 (user_id), INDEX IDX_AFCF975ED725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tempagence (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, agence_id INT NOT NULL, generale TINYINT(1) NOT NULL, INDEX IDX_30A8D1D2A76ED395 (user_id), INDEX IDX_30A8D1D2D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE transferta (id INT AUTO_INCREMENT NOT NULL, produit_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, user_id INT DEFAULT NULL, quantite DOUBLE PRECISION NOT NULL, reste DOUBLE PRECISION NOT NULL, createtAt DATE NOT NULL, statut VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, matricule VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, Employer_id INT DEFAULT NULL, INDEX IDX_C029B9F3A76ED395 (user_id), INDEX IDX_C029B9F3C75111AD (Employer_id), INDEX IDX_C029B9F3D725330D (agence_id), INDEX IDX_C029B9F3F347EFB (produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tresoreriea (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, libelles VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, net DOUBLE PRECISION NOT NULL, createtAt DATE NOT NULL, ordre INT NOT NULL, INDEX IDX_90D006D0A76ED395 (user_id), INDEX IDX_90D006D0D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ventea (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, user_id INT DEFAULT NULL, produit_id INT DEFAULT NULL, agence_id INT DEFAULT NULL, type VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, quantite DOUBLE PRECISION NOT NULL, prix DOUBLE PRECISION NOT NULL, createAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', cash DOUBLE PRECISION NOT NULL, reduction DOUBLE PRECISION NOT NULL, banque DOUBLE PRECISION NOT NULL, statut VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, credit DOUBLE PRECISION NOT NULL, heure VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, momo DOUBLE PRECISION NOT NULL, esperce VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, om DOUBLE PRECISION NOT NULL, reference VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_AB971C2C19EB6921 (client_id), INDEX IDX_AB971C2CA76ED395 (user_id), INDEX IDX_AB971C2CD725330D (agence_id), INDEX IDX_AB971C2CF347EFB (produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE versementa (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, user_id INT NOT NULL, agence_id INT DEFAULT NULL, montant DOUBLE PRECISION NOT NULL, om DOUBLE PRECISION NOT NULL, banque DOUBLE PRECISION NOT NULL, createdAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', description VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_4F23073319EB6921 (client_id), INDEX IDX_4F230733A76ED395 (user_id), INDEX IDX_4F230733D725330D (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE achata ADD CONSTRAINT FK_565BC6F83AAF8973 FOREIGN KEY (forunisseur_id) REFERENCES fournisseura (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE achata ADD CONSTRAINT FK_565BC6F8A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE achata ADD CONSTRAINT FK_565BC6F8D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE achata ADD CONSTRAINT FK_565BC6F8F347EFB FOREIGN KEY (produit_id) REFERENCES produita (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE actifa ADD CONSTRAINT FK_3A730FB4A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE actifa ADD CONSTRAINT FK_3A730FB4D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE balancea ADD CONSTRAINT FK_7006D7D922A5DBC9 FOREIGN KEY (passifA_id) REFERENCES passifa (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE balancea ADD CONSTRAINT FK_7006D7D9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE balancea ADD CONSTRAINT FK_7006D7D9D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE balancea ADD CONSTRAINT FK_7006D7D9EA82AF8F FOREIGN KEY (ActifA_id) REFERENCES actifa (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE bondcommande ADD CONSTRAINT FK_58BE72D7F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE bondcommandea ADD CONSTRAINT FK_CB36678EF347EFB FOREIGN KEY (produit_id) REFERENCES produita (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE caissea ADD CONSTRAINT FK_89694EC6A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE caissea ADD CONSTRAINT FK_89694EC6D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE credit_fourniseur ADD CONSTRAINT FK_AD9F5770670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE credit_fourniseur ADD CONSTRAINT FK_AD9F5770A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE credit_fourniseur ADD CONSTRAINT FK_AD9F5770D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depensea ADD CONSTRAINT FK_DF943D1DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depensea ADD CONSTRAINT FK_DF943D1DD725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depenseactif ADD CONSTRAINT FK_C6402A2440E1C722 FOREIGN KEY (actif_id) REFERENCES actif (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depenseactif ADD CONSTRAINT FK_C6402A24A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depenseactif ADD CONSTRAINT FK_C6402A24D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depenseactifa ADD CONSTRAINT FK_EF1C3A7040E1C722 FOREIGN KEY (actif_id) REFERENCES actifa (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depenseactifa ADD CONSTRAINT FK_EF1C3A70A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depenseactifa ADD CONSTRAINT FK_EF1C3A70D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depensepassif ADD CONSTRAINT FK_F3A20F9549B26346 FOREIGN KEY (passif_id) REFERENCES passif (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depensepassif ADD CONSTRAINT FK_F3A20F95A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depensepassif ADD CONSTRAINT FK_F3A20F95D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depensepassifa ADD CONSTRAINT FK_534F5B4F49B26346 FOREIGN KEY (passif_id) REFERENCES passifa (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depensepassifa ADD CONSTRAINT FK_534F5B4FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depensepassifa ADD CONSTRAINT FK_534F5B4FD725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE employer_agence ADD CONSTRAINT FK_3B8E660E41CD9E7A FOREIGN KEY (employer_id) REFERENCES employer (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employer_agence ADD CONSTRAINT FK_3B8E660ED725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE emprunta ADD CONSTRAINT FK_322EFBDBA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE emprunta ADD CONSTRAINT FK_322EFBDBD725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE facturea ADD CONSTRAINT FK_37E66ADD19EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE facturea ADD CONSTRAINT FK_37E66ADD7DC7170A FOREIGN KEY (vente_id) REFERENCES ventea (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE facturea ADD CONSTRAINT FK_37E66ADDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE facturea ADD CONSTRAINT FK_37E66ADDD725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE facturea ADD CONSTRAINT FK_37E66ADDF347EFB FOREIGN KEY (produit_id) REFERENCES produita (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE fournisseura ADD CONSTRAINT FK_3098A39A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE fournisseura ADD CONSTRAINT FK_3098A39D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE fournisseura_produita ADD CONSTRAINT FK_E8A4154A37013DDB FOREIGN KEY (produita_id) REFERENCES produita (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fournisseura_produita ADD CONSTRAINT FK_E8A4154ADDBC42E9 FOREIGN KEY (fournisseura_id) REFERENCES fournisseura (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE historiquea ADD CONSTRAINT FK_FC1400DA973392E5 FOREIGN KEY (produitA_id) REFERENCES produita (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE historiquea ADD CONSTRAINT FK_FC1400DAD725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE immobilisationa ADD CONSTRAINT FK_FEA74340A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE immobilisationa ADD CONSTRAINT FK_FEA74340D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE inventairea ADD CONSTRAINT FK_F57C7A04A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE inventairea ADD CONSTRAINT FK_F57C7A04D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE inventairea ADD CONSTRAINT FK_F57C7A04F347EFB FOREIGN KEY (produit_id) REFERENCES produita (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE inventairecaissea ADD CONSTRAINT FK_FDAE5AB1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE inventairecaissea ADD CONSTRAINT FK_FDAE5AB1D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE magasina ADD CONSTRAINT FK_8FF1E6E9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE magasina ADD CONSTRAINT FK_8FF1E6E9D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE magasina ADD CONSTRAINT FK_8FF1E6E9F347EFB FOREIGN KEY (produit_id) REFERENCES produita (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE passifa ADD CONSTRAINT FK_CF9332D3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE passifa ADD CONSTRAINT FK_CF9332D3D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE produita ADD CONSTRAINT FK_8F8CEC5AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE produita ADD CONSTRAINT FK_8F8CEC5AD725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE prospectiona ADD CONSTRAINT FK_CE1D2EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE prospectiona ADD CONSTRAINT FK_CE1D2ED725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE quantiteproduita ADD CONSTRAINT FK_ACCD6C6C7DC7170A FOREIGN KEY (vente_id) REFERENCES ventea (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE quantiteproduita ADD CONSTRAINT FK_ACCD6C6CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE quantiteproduita ADD CONSTRAINT FK_ACCD6C6CF347EFB FOREIGN KEY (produit_id) REFERENCES produita (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE remboursementa ADD CONSTRAINT FK_2EC8D963A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE remboursementa ADD CONSTRAINT FK_2EC8D963AE7FEF94 FOREIGN KEY (emprunt_id) REFERENCES emprunta (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE remboursementa ADD CONSTRAINT FK_2EC8D963D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE retraita ADD CONSTRAINT FK_361A19D555D4B1AE FOREIGN KEY (Agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE retraita ADD CONSTRAINT FK_361A19D5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE salairea ADD CONSTRAINT FK_4024179241CD9E7A FOREIGN KEY (employer_id) REFERENCES employer (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE salairea ADD CONSTRAINT FK_40241792A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE salairea ADD CONSTRAINT FK_40241792D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE socialesa ADD CONSTRAINT FK_AFCF975EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE socialesa ADD CONSTRAINT FK_AFCF975ED725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE tempagence ADD CONSTRAINT FK_30A8D1D2A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE tempagence ADD CONSTRAINT FK_30A8D1D2D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE transferta ADD CONSTRAINT FK_C029B9F3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE transferta ADD CONSTRAINT FK_C029B9F3C75111AD FOREIGN KEY (Employer_id) REFERENCES employer (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE transferta ADD CONSTRAINT FK_C029B9F3D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE transferta ADD CONSTRAINT FK_C029B9F3F347EFB FOREIGN KEY (produit_id) REFERENCES produita (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE tresoreriea ADD CONSTRAINT FK_90D006D0A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE tresoreriea ADD CONSTRAINT FK_90D006D0D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE ventea ADD CONSTRAINT FK_AB971C2C19EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE ventea ADD CONSTRAINT FK_AB971C2CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE ventea ADD CONSTRAINT FK_AB971C2CD725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE ventea ADD CONSTRAINT FK_AB971C2CF347EFB FOREIGN KEY (produit_id) REFERENCES produita (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE versementa ADD CONSTRAINT FK_4F23073319EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE versementa ADD CONSTRAINT FK_4F230733A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE versementa ADD CONSTRAINT FK_4F230733D725330D FOREIGN KEY (agence_id) REFERENCES agence (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE depenses DROP reference');
    }
}
